# Generated by Django 6.0.5 on 2026-05-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('songs_count', models.IntegerField(blank=True, null=True, verbose_name='Количество песен')),
                ('artist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='artists.genre')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название песни')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('album', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='Альбом')),
                ('artist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='Исполнитель')),
                ('genre', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='artists.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
