# Generated by Django 6.0.2 on 2026-04-01 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название песни')),
                ('album', models.CharField(blank=True, max_length=255, null=True, verbose_name='Альбом')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
