# Generated by Django 6.0.2 on 2026-04-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_genre'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название альбома')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр')),
                ('songs_count', models.IntegerField(blank=True, null=True, verbose_name='Количество песен')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
