# Generated by Django 6.0.2 on 2026-04-03 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_rename_year_of_debut_artist_active_years'),
        ('music', '0003_alter_album_artist_alter_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='artists.genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='artists.genre'),
        ),
    ]
