# Generated by Django 6.0.2 on 2026-04-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_album_artist_remove_album_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
