# Generated by Django 6.0.4 on 2026-04-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rename_album_id_song_album_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
