# Generated by Django 6.0.4 on 2026-05-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0017_artist_photo'),
        ('music', '0007_alter_song_album_alter_song_artist_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='artists.genre', verbose_name='Жанр'),
        ),
    ]
