# Generated by Django 6.0.5 on 2026-05-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255, verbose_name='Название фан-клуба')),
                ('founded', models.CharField(max_length=255, verbose_name='Дата основания')),
                ('members', models.IntegerField(verbose_name='Количество участников')),
                ('description', models.TextField(verbose_name='Описание')),
                ('artist', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Фан-клуб',
                'verbose_name_plural': 'Фан-клубы',
                'ordering': ['-members'],
            },
        ),
    ]
