# Generated by Django 6.0.2 on 2026-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='founded',
            field=models.CharField(max_length=255, verbose_name='Дата основания'),
        ),
    ]
