# Generated by Django 6.0.2 on 2026-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='artist',
            field=models.CharField(max_length=255, verbose_name='Исполнитель'),
        ),
    ]
