# Generated by Django 6.0.2 on 2026-04-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_rename_genre_artist_genre_id'),
        ('communities', '0003_alter_community_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
        ),
    ]
