# Generated by Django 6.0.2 on 2026-04-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_community_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='artist',
            new_name='artist_id',
        ),
    ]
