# Generated by Django 6.0.2 on 2026-04-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_rename_artist_community_artist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
