# Generated by Django 6.0.2 on 2026-04-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_alter_artist_tags'),
        ('communities', '0006_rename_artist_id_community_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='artist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.artist'),
        ),
    ]
