# Generated by Django 6.0.4 on 2026-05-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_alter_artist_options_alter_genre_options_and_more'),
        ('communities', '0007_alter_community_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='artist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.artist', verbose_name='Исполнитель'),
        ),
    ]
