# Generated by Django 6.0.2 on 2026-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='year_of_debut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
