# Generated by Django 6.0.2 on 2026-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_artist_year_of_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(max_length=10),
        ),
    ]
