# Generated by Django 6.0.2 on 2026-04-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_artist_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='year_of_debut',
            field=models.CharField(blank=True, null=True),
        ),
    ]
