# Generated by Django 6.0.2 on 2026-04-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_alter_artist_year_of_debut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='year_of_debut',
            new_name='active_years',
        ),
    ]
