# Generated by Django 6.0.2 on 2026-04-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_alter_artist_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='genre',
            new_name='genre_id',
        ),
    ]
