# Generated by Django 6.0.2 on 2026-04-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_rename_genre_artist_genre_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
