# Generated by Django 6.0.2 on 2026-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_rename_genre_id_artist_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='artists.tagpost'),
        ),
    ]
