# Generated by Django 6.0.2 on 2026-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_tagpost_artist_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artists.tagpost'),
        ),
    ]
