# Generated by Django 6.0.2 on 2026-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_alter_artist_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='active_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='active_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
