# Generated by Django 6.0.2 on 2026-04-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_artist_active_from_artist_active_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='active_years',
        ),
    ]
