# Generated by Django 6.0.4 on 2026-05-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_remove_artist_active_years'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='active_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Активен с'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='active_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Активен по'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='artists.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artists', to='artists.tagpost', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='tag',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Тег'),
        ),
    ]
