# Generated by Django 6.0.4 on 2026-05-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_alter_artist_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
    ]
