# Generated by Django 6.0.2 on 2026-04-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('album', 'Альбом'), ('song', 'Песня')], max_length=10, verbose_name='Тип рецензии')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст рецензии')),
                ('date', models.CharField(max_length=50, verbose_name='Дата публикации')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='Исполнитель')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
                'ordering': ['-date'],
            },
        ),
    ]
