# Generated by Django 6.0.5 on 2026-06-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'permissions': [('can_edit_comment', 'Может редактировать комментарии'), ('can_delete_comment', 'Может удалять комментарии')], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
