# Generated by Django 6.0.2 on 2026-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='artist',
            field=models.CharField(max_length=255, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(max_length=10, verbose_name='Жанр'),
        ),
    ]
