# Generated by Django 6.0.2 on 2026-04-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_rename_genre_id_artist_genre'),
        ('reviews', '0004_alter_review_artist_alter_review_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='artists.genre', verbose_name='Жанр'),
        ),
    ]
