# Generated by Django 6.0.4 on 2026-04-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rename_album_id_song_album_and_more'),
        ('reviews', '0005_alter_review_artist_alter_review_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='review',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='type',
        ),
        migrations.AddField(
            model_name='review',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='music.album'),
        ),
        migrations.AddField(
            model_name='review',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='music.song'),
        ),
    ]
