# Generated by Django 6.0.4 on 2026-04-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_rename_album_id_song_album_and_more'),
        ('reviews', '0007_alter_review_album_alter_review_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='album',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.album'),
        ),
        migrations.AlterField(
            model_name='review',
            name='song',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.song'),
        ),
    ]
