# Generated by Django 6.0.4 on 2026-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_review_album_alter_review_song_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка рецензии'),
        ),
    ]
